annotations:
  catalog.cattle.io/display-name: Kyverno (1/1) - Operator
  catalog.cattle.io/os: linux
  catalog.cattle.io/permits-os: linux
#  catalog.cattle.io/kube-version: '>=1.26.0-0 < 1.31.0-0'
#  catalog.cattle.io/rancher-version: '>= 2.8.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: kyverno-operator
apiVersion: v2
appVersion: 3.4.3
dependencies:
  - name: common
    repository: https://charts.sourcemation.com/
    version: 0.1.x
  - name: kyverno
    version: 3.4.3
    repository: https://kyverno.github.io/kyverno/
description: Kyverno is a policy management solution for Kubernetes and other cloud native environments. Install only once on kubernetes. Security.
home: https://linuxpolska.com
icon: https://linuxpolska.com/logo/LinuxPolska-icon.png
keywords:
  - security
  - kyverno
#kubeVersion: '>=1.26.0-0 <1.31.0-0'
maintainers:
  - email: radoslaw.kolba@linuxpolska.com
    name: radkolba-lp
name: kyverno-operator
sources:
  - https://github.com/Sourcemation/charts.git
type: application
version: 0.1.3
